### ISSUE TITLE
Models to Icons issue

### ISSUE THREAD

**Issue by raidaddicts** [Akkadius/spire#102]
When you pick an item model and then try and have it select the icon , sometimes it will work fine but other times it won't as shown here:

https://user-images.githubusercontent.com/13406868/217960486-529339cc-d8e8-4bc1-8967-19b60f967e6b.mp4

**Comment by Akkadius** [comment]
Icon and model searches do look-ups by what you currently have in your database. It's looking for items already in your database that have those kind of pairings and matches. It's only going to be as accurate as the data you have.

I don't use a pre-determined built list of what icons get match to what items otherwise
