### ISSUE TITLE
Icon's to Models issue

### ISSUE THREAD

**Issue by raidaddicts** [Akkadius/spire#103]
Same as the other issue I posted, sometimes when you pick an icon then have it try to find the model it just doesn't work or shows some bag or incorrect item instead. 
(Shown here)

https://user-images.githubusercontent.com/13406868/217960983-1806fe5a-236b-4695-bb74-550d15b1b588.mp4

**Comment by Akkadius** [comment]
Icon and model searches do look-ups by what you currently have in your database. It's looking for items already in your database that have those kind of pairings and matches. It's only going to be as accurate as the data you have. 

I don't use a pre-determined built list of what icons get match to what items otherwise
