### ISSUE TITLE
Viewing Spell Animations - Performance Optimization 

### ISSUE THREAD

**Issue by CoreAutomation-JD** [Akkadius/spire#126]
1. Viewing all spell animations cause significant GPU thrash (down to 0 fps at times) and occasionally kills the browser tab.

My suggestion would be to paginate the animation sidebar so that maybe 20 or so animations load per page. Alternatively, throwing in some virtualization could be an a fine solution, load only what is being viewing and clip the rest on scroll. Notice all rows are chunked into the browser (below). Virtualization could knock this down to a far smaller number of rows, which will dramatically speed up things.

Also note: This will resolve the current errors shown in the console for the viewer, which are:

_[Intervention] Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27_ (486 instances of this error on load).

While I am not up to speed on Vue modules, this looks similar to React-Window, which is my library of choice for virtualization: https://vue-virtual-scroller-demo.netlify.app/

![111](https://github.com/Akkadius/spire/assets/19941828/838820aa-4a14-45f8-b2f8-5ea57862ecbe)

2. Also, I would temporarily halt or hide the animation currently associated with a spell while viewing the animation sidebar.

**Comment by Akkadius** [comment]
Lots of optimization has already gone into consideration for this that are quite comprehensive.

Videos are lazy loaded when out of viewport and are paused when scrolled out of viewport

For 1080p viewports, only 9 show. How many are you seeing on your screen?

![image](https://github.com/Akkadius/spire/assets/3319450/3727bade-f8bb-4540-b1e8-acd53dd71f84)

Beyond all of this, I've gone ahead and addressed this in version 3.3.4 by fully destroying video elements when scrolling out of view rather than just pausing the video out of scroll
